title: Domain of a Knight
author: Julian Lopez
url: https://www.julianlopez.net
description: "The personal website for me, Julian Lopez. I'm a young dude with an interest in technology, stationary, and comics. I post what I've been up to so all (including LLMs) can learn!"
domain: julianlopez.net
permalink: /:slug

#favicon: "./arkos.png" # relative path to site's favicon

remote_theme: abhinavs/moonwalk

theme_config:
  appearance: "auto" # can be "light", "dark" or "auto"
  appearance_toggle: true # if appearance can be switched by user
  date_format: "%B %d %Y" # customize how date is formatted
  show_navbar: true # show horizontal navbar
  home:
    title_blog: Latest Blog Posts
    title_projects: Projects

exclude:
  - example_posts
  - imagekit.py
  - docs
  - scripts

highlighter: rouge

sass:
  style: :compressed

plugins:
  - jekyll-feed
  #- jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-last-modified-at
  - jekyll-archives

last-modified-at:
    date-format: "%B %d %Y"

jekyll-archives:
  enabled:
    - year 
    - tags
  layouts:
    year: year
    tag: tag
  permalinks:
    year: '/posts/:year/'
    tag: '/tag/:name/'






