title: Domain of a Knight
author: Julian Lopez
url: https://www.julianlopez.net
description: "The personal website for me, Julian Lopez. Sometimes I go by the name Rerun. I'm a young dude with interests in technology, stationary, fountain pens, wheelchairs, postage, and comics."
domain: julianlopez.net
permalink: /:slug

#favicon: "./arkos.png" # relative path to site's favicon

# remote_theme: abhinavs/moonwalk

theme_config:
  date_format: "%B %d %Y" # customize how date is formatted

exclude:
  - docs
  - _data/most_recent_mastodon_post.yml

highlighter: rouge

sass:
  style: :compressed

plugins:
  # - jekyll-feed
  #- jekyll-seo-tag
  - jekyll-sitemap
  # - jekyll-last-modified-at
  - jekyll-archives

# last-modified-at:
    # date-format: "%B %d %Y"

jekyll-archives:
  enabled:
    - year 
    - tags
  layouts:
    year: year
    tag: tag
  permalinks:
    year: '/posts/:year/'
    tag: '/tag/:name/'

# verbose: true

timezone: America/Los_Angeles